version: '2'
services:
    api:
        build: api
        ports:
            - "8001:8001"
        env_file: .env
        depends_on:
            - redis
    web:
        build: web
        ports:
            - "8000:8000"
        env_file: .env
        depends_on:
            - redis
            - api
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"